Make the dockerfile VERSION argument mandatory
Change-Id: Ia77e8f0132dd9cd0bb38914f75093cd7750257c3
Reviewed-on: https://review.couchbase.org/c/couchbase-elasticsearch-connector/+/167975
Tested-by: David Nault <david.nault@couchbase.com>
Reviewed-by: David Nault <david.nault@couchbase.com>

diff --git a/Dockerfile.download b/Dockerfile.download
--- a/Dockerfile.download
+++ b/Dockerfile.download
@@ -1,11 +1,12 @@
-# Builds an image using a pre-built connector distribution archive from couchbase.com
+# Builds an image using a pre-built connector distribution archive from couchbase.com.
 
 # First stage downloads and unzips the connector distribution archive
 FROM redhat/ubi8-minimal:latest AS build
 
 # Version of the connector to download. See release notes for valid versions
 # https://docs.couchbase.com/elasticsearch-connector/current/release-notes.html
-ARG VERSION=4.3.4
+ARG VERSION
+RUN [ -z "$VERSION" ] && echo "Missing VERSION argument. Must specify like: --build-arg VERSION=<connector-version>" && exit 1 || true
 
 RUN curl -s https://packages.couchbase.com/clients/connectors/elasticsearch/${VERSION}/couchbase-elasticsearch-connector-${VERSION}.zip -o /couchbase-elasticsearch-connector.zip
 RUN microdnf install unzip
